apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  labels:
    app: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: nginx:local
          ports:
            - containerPort: 80
          volumeMounts:
            - name: resume-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: resume-html
          configMap:
            name: resume-html
